jobs:
  call-translate:
    uses: shaoting0730/mobile-learn/blob/master/.github/workflows/translate.yml@main
    with:
      file: README.md
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
