name: Call Translate README

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  call-translate:
    uses: shaoting0730/mobile-learn/.github/workflows/translate-readme.yml@main
    with:
      file: README.md
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
