name: Call Translate Workflow

on:
  workflow_dispatch: {} # 手动触发
  push:
    paths:
      - README.md # 当 README.md 改动时自动触发

jobs:
  call-translate:
    uses: shaoting0730/shaoting0730/.github/workflows/translate-readme.yml@main
    with:
      file: README.md # ✅ 和被调用方的 inputs.file 一致
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
